### ISSUE TITLE
Create Eslint check for all pull-requests using GitHub action

### ISSUE THREAD

**Issue by dev-nguyenhoanganh** [dev-nguyenhoanganh/ecommerce-client#31]
**Describe the solution you'd like**
Create Eslint check for all pull-requests using GitHub action

**Describe alternatives you've considered**
Please make a consideration
```yaml
on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: apps # only if a different glob is needed, default: src
```
https://github.com/marketplace/actions/eslint-js-ts-action

**Additional context**
Not yet
